### ISSUE TITLE
Add support for `GET` and `PATCH` for NSX Group

### ISSUE THREAD

**Issue by antonystefanov** [vmware/power-validated-solutions-for-cloud-foundation#212]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Add functions to:

`GET` the NSX-T group identified by name from the NSX-T inventory, using API call: 

```
https://<nsxtmanager>/policy/api/v1/infra/domains/default/groups/<GroupName>
```

`PATCH` NSX-T group identified by name, using API call: 

```
https://<nsxtmanager>/policy/api/v1/infra/domains/default/groups/<GroupName>
```

### Use Case(s)

1. Get the NSX-T group, modify it and PATCH it back.
2. Copy NSX-T group from one NSX-T LM to another

### Potential Configuration

```powershell
function Get-NsxtGroup {
    param (
        [Parameter (Mandatory = $true)] [String]$Name
    )

    Try {
        $requestingURL = "https://$nsxtmanager/policy/api/v1/infra/domains/default/groups/" + $Name
        $response = Invoke-RestMethod -Method GET -URI $requestingURL -ContentType application/json -headers $nsxtHeaders # -SkipCertificateCheck
        $response
    }
    Catch {
        Write-Error $_.Exception.Message
    }
    
}
```

```powershell
function Patch-NsxtGroup {
    param (
        [Parameter (Mandatory = $true)] [String]$groupId,
        [Parameter (Mandatory = $true)] [String]$name,
        [Parameter (Mandatory = $false)] [String]$description,
        [Parameter (Mandatory = $true)] $expressionJson
    )

    $expression = $expressionJson | ConvertFrom-Json
    $desc = ""
    
    if ($description) {$desc = $description}

    switch ($expression.resource_type) {
        
        { ($_ -eq "IPAddressExpression") -or ($_ -eq "Condition") -or ($_ -eq "NestedExpression") } {

            $groupJson = @"
{
    "expression" : [
        $expressionJson
        ],

    "resource_type" : "Group",
    "id" : "$name",
    "display_name" : "$name",
    "description" : "$desc"
}
"@
            
        }

        default {
            Write-LogMessage -type ERROR -Message "Unsupported expression type: $($expression.resource_type)" -Colour Red
            exit
        }

    }

    
    Try {
        $requestingURL = "https://$nsxtmanager/policy/api/v1/infra/domains/default/groups/" + $groupId
        $Response = Invoke-RestMethod -Method PATCH -URI $requestingURL -ContentType application/json -headers $nsxtHeaders -body $groupJson #-SkipCertificateCheck
        $response
    }
    Catch {
        Write-Error $_.Exception.Message
    }

}
```

**Comment by tenthirtyam** [comment]
@antonystefanov were you going to submit a pull request for this issue?

**Comment by tenthirtyam** [comment]
Hi, @antonystefanov 👋

I am checking in to see if you plan to submit a pull request for this enhancement request.

Thanks!
Ryan

**Comment by GaryJBlake** [comment]
Closing this issue, no use case for VMware Validated Solutions to implement this. @antonystefanov if you think there is still value in adding this functionality then please fork the repository, develop the code and make a pull request.
