### ISSUE TITLE
Add support for `GET` and `PATCH` for NSX Security Policy

### ISSUE THREAD

**Issue by antonystefanov** [vmware/power-validated-solutions-for-cloud-foundation#213]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Add support to GET the NSX-T security policy using the API call path: 

```
https://<nsxtmanager>/policy/api/v1/infra/domains/default/security-policies/<policyId>
```

Add support to PATCH the NSX-T security policy using the API call path: 

```
https://<nsxtmanager>/policy/api/v1/infra/domains/default/security-policies/<policyId>
```

### Use Case(s)

`GET` NSX-T security policy to modify it and `PATCH` it back.

Copy NSX-T security policy from one NSX-T LM to another NSX-T LM.

### Potential Configuration

```powershell
function Get-NsxtSecurityPolicy {
    param (
        [Parameter (Mandatory = $true)] [String]$name
    )
    $policyId = $name.replace(" ", "_")
    Try {
        $requestingURL = "https://$nsxtmanager/policy/api/v1/infra/domains/default/security-policies/" + $policyId
        Write-LogMessage -type INFO -Message "Getting from $requestingURL"
        $response = Invoke-RestMethod -Method GET -URI $requestingURL -ContentType application/json -headers $nsxtHeaders # -SkipCertificateCheck
        $response
    }
    Catch {
        Write-Error $_.Exception.Message
    }   

}
```

```powershell
function Patch-NsxtSecurityPolicy {
    param (
        [Parameter (Mandatory = $true)] [String]$name,
        [Parameter (Mandatory = $true)] [String]$displayName,
        [Parameter (Mandatory = $true)] [String]$category,
        [Parameter (Mandatory = $true)] $rulesJson
    )
    $json = @"
{
    "description": "$name",
    "display_name": "$displayName",
    "category": "$category",
    "rules": 
        $rulesJson
}
"@
    $policyId = $name.replace(" ", "_")
    Try {
        $requestingURL = "https://$nsxtmanager/policy/api/v1/infra/domains/default/security-policies/" + $policyId
        
        $response = Invoke-RestMethod -Method PATCH -URI $requestingURL -ContentType application/json -headers $nsxtHeaders -body $json # -SkipCertificateCheck
        $response
    }
    Catch {
        Write-Error $_.Exception.Message
    }
    
}
```

**Comment by tenthirtyam** [comment]
Hi, @antonystefanov 👋

I am checking in to see if you plan to submit a pull request for this enhancement request.

Thanks!
Ryan

**Comment by GaryJBlake** [comment]
Closing this issue, no use case for VMware Validated Solutions to implement this. @antonystefanov if you think there is still value in adding this functionality then please fork the repository, develop the code and make a pull request.
