### ISSUE TITLE
`Add-vROPSAdapterIdentityManager` error: "The property 'adapter-certificates' cannot be found on this object. Verify that the property exists and can be set."

### ISSUE THREAD

**Issue by cybernils** [vmware/power-validated-solutions-for-cloud-foundation#228]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

4.5.0

### Module Version

2.0.0.1010

### PowerShell Version

5.1.19041.2364

### PowerCLI Version

12.7.0

### PowerVCF Version

2.2.0

### Guest Operating System

Windows 10

### Description

```
Add-vROPSAdapterIdentityManager -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -wsaFqdn $wsaFqdn -wsaUser $wsaUser -wsaPass $wsaPass -collectorGroupName $remoteCollectorGroup
 Error at Script Line 10757
 Relevant Command: $adapterDetail.'adapter-certificates' = $adapterDetail.'adapter-certificates' | Select-Object * -ExcludeProperty certificateDetails
 Error Message: Exception setting "adapter-certificates": "The property 'adapter-certificates' cannot be found on this object. Verify that the property exists and can be set."
```

### Error or Debug Output

```
Add-vROPSAdapterIdentityManager -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -wsaFqdn $wsaFqdn -wsaUser $wsaUser -wsaPass $wsaPass -collectorGroupName $remoteCollectorGroup
 Error at Script Line 10757
 Relevant Command: $adapterDetail.'adapter-certificates' = $adapterDetail.'adapter-certificates' | Select-Object * -ExcludeProperty certificateDetails
 Error Message: Exception setting "adapter-certificates": "The property 'adapter-certificates' cannot be found on this object. Verify that the property exists and can be set."
```

### Expected Behavior

No error.

### Actual Behavior

```
Add-vROPSAdapterIdentityManager -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -wsaFqdn $wsaFqdn -wsaUser $wsaUser -wsaPass $wsaPass -collectorGroupName $remoteCollectorGroup
 Error at Script Line 10757
 Relevant Command: $adapterDetail.'adapter-certificates' = $adapterDetail.'adapter-certificates' | Select-Object * -ExcludeProperty certificateDetails
 Error Message: Exception setting "adapter-certificates": "The property 'adapter-certificates' cannot be found on this object. Verify that the property exists and can be set."
```

### Steps to Reproduce

`Add-vROPSAdapterIdentityManager -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -wsaFqdn `

**Comment by GaryJBlake** [comment]
Unable to reproduce this issue in our lab

**Comment by GaryJBlake** [comment]
After upgrading to vRealize Operations 8.10.2 I'm now able to reproduce this issue in our lab. Further investigation needed.
