### ISSUE TITLE
bug: VCF5.0- Isolated WLD- Unable to find (svc-vra-vsphere) in vCenter Server (sfo-w01-vc01): PRE_VAILIDATION_FAILED

### ISSUE THREAD

**Issue by slakshmanan2706** [vmware/power-validated-solutions-for-cloud-foundation#315]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.0

### Module Version

2.6.0.1001

### PowerShell Version

7.3.6

### PowerCLI Version

13.1

### PowerVCF Version

2.3.0.1004

### Guest Operating System

windows server 2019

### Environment Details

VCF 5.0 with isolated WLD

### Description

https://docs.vmware.com/en/VMware-Cloud-Foundation/services/vcf-private-cloud-automation-v1/GUID-47B20817-952F-4820-BDA6-F2CC4B74E66A.html

Set-vCenterPermission fails with below error message.

```pwoershell

PS F:\platformtools> Set-vCenterPermission -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -domain $domainAlias -workloadDomain $sddcDomainName -principal $vraServiceAccount -role "NoAccess" -folderName $nsxEdgeVMFolder -folderType "VM"
Set-vCenterPermission: Unable to find (svc-vra-vsphere) in vCenter Server (sfo-w01-vc01): PRE_VAILIDATION_FAILED
PS F:\platformtools>

```

### Error or Debug Output

```pwoershell

PS F:\platformtools> Set-vCenterPermission -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -domain $domainAlias -workloadDomain $sddcDomainName -principal $vraServiceAccount -role "NoAccess" -folderName $nsxEdgeVMFolder -folderType "VM"
Set-vCenterPermission: Unable to find (svc-vra-vsphere) in vCenter Server (sfo-w01-vc01): PRE_VAILIDATION_FAILED
PS F:\platformtools>

```

### Expected Behavior

should be successful. 

### Actual Behavior

```pwoershell

PS F:\platformtools> Set-vCenterPermission -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -domain $domainAlias -workloadDomain $sddcDomainName -principal $vraServiceAccount -role "NoAccess" -folderName $nsxEdgeVMFolder -folderType "VM"
Set-vCenterPermission: Unable to find (svc-vra-vsphere) in vCenter Server (sfo-w01-vc01): PRE_VAILIDATION_FAILED
PS F:\platformtools>

```

### Steps to Reproduce

Deploy VCF 5.0 with WLD in isolated mode.
Deploy vRSLCM and VRA
Perform the steps https://docs.vmware.com/en/VMware-Cloud-Foundation/services/vcf-private-cloud-automation-v1/GUID-47B20817-952F-4820-BDA6-F2CC4B74E66A.html

**Comment by GaryJBlake** [comment]
Reason: At the current time no VMware Validated Solutions have been fully validated with an Isolated Workload Domain, automation failures are to be expected but before we can address any automation issues there is significant work required to review and update the manual procedures in the context of an Isolated Workload Domain.

Marking this issues as Declined/Closed but tracking issue internally pending further analysis / review of the Isolated Workload Domain use case.
