### ISSUE TITLE
`Test-VrmsVamiAuthentication` fails with error: Cannot bind argument to parameter 'Exception' because it is null

### ISSUE THREAD

**Issue by slakshmanan2706** [vmware/power-validated-solutions-for-cloud-foundation#322]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.0

### Module Version

2.6.0.1005

### PowerShell Version

7.3.6

### PowerCLI Version

13.1

### PowerVCF Version

2.3.0.1004

### Guest Operating System

windows server 2019

### Environment Details

windows server 2019 + PS7

RDP : 10.158.130.138/ administrator /VMw@re1!

### Description

PT option 30 94 15. vSphere Replication: Register vSphere Replication with vCenter Single Sign-On

PT option 30 94 23. Site Recovery Manager: Register Site Recovery Manager with vCenter Single Sign-On

shows below error message:
VR 
```Powershell
 Version 5.0.9.1030 | Environment Type: DualRegion-SingleAZ | Management Domain Tasks: Site Protection and Disaster Recovery

 [08-10-2023_20:48:31] [...] [NOTE] Starting the Process of Registering vSphere Replication with vCenter Single Sign-On
 [08-10-2023_20:48:34] [...] [INFO] Attempting to Register vSphere Replication Appliance (sfo-m01-vrms01.sfo.rainpole.io) with vCenter Single Sign-On
 [08-10-2023_20:51:19] [...] [INFO]  Error at Script Line 1697  Relevant Command: $vamiStatus = Test-VrmsVamiAuthentication -server $applianceFqdn -user admin -pass $vamiAdminPassword -ErrorAction SilentlyContinue  Error Message: Cannot bind argument to parameter 'Exception' because it is null.
 [08-10-2023_20:51:19] [...] [NOTE] Finished the Process of Registering vSphere Replication with vCenter Single Sign-On

 Press any key to continue/return to menu...

```

SRM 
```Powershell
 

INFO] Attempting to Register Site Recovery Manager Appliance (sfo-m01-srm01.sfo.rainpole.io) with vCenter Single Sign-On
--
 INFO - [08-10-2023_20:48:28] [...] [INFO] Error at Script Line 1717 Relevant Command: $vamiStatus = Test-VrmsVamiAuthentication -server $applianceFqdn -user admin -pass $vamiAdminPassword -ErrorAction SilentlyContinue Error Message: Cannot bind argument to parameter 'Exception' because it is null.

 
```
Refer : https://racetrack.eng.vmware.com/resultdetails.php?id=1264625827&resultid=25949560&view=false&failonly=No 

### Error or Debug Output

Please refer the error message

### Expected Behavior

Config should work without any error message,

### Actual Behavior

shows an error message 

### Steps to Reproduce

Deploy SRM and VR via PT
perform PT option 30 94 15 or 23 

### Screenshots

Though it showed the error actual registration went fine  with VC . Please refer the screenshot. 

![image](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/assets/85702650/06232292-c835-4ab4-9890-075f78797da8)

**Comment by slakshmanan2706** [comment]
Same error is observed for option 17. vSphere Replication: Add a Network Adapter and Configure Static Routes for vSphere Replication

```
8/10 1:17:56 pm | [ConfigUsingPlatformTools.py:114] - [2023-08-10 21:16:50] INFO - [08-10-2023_21:16:37] [...] [NOTE] Starting the Process of Adding a Network Adapter and Configure Static Routes for vSphere Replication
-- | --
8/10 1:17:57 pm | [ConfigUsingPlatformTools.py:114] - [2023-08-10 21:16:50] INFO - [08-10-2023_21:16:37] [...] [INFO] Attempting to Add a Network Adapter and Configure Static Routes for vSphere Replication
8/10 1:17:57 pm | [ConfigUsingPlatformTools.py:114] - [2023-08-10 21:16:50] INFO - [08-10-2023_21:16:50] [...] [INFO] Error at Script Line 1937 Relevant Command: $vamiStatus = Test-VrmsVamiAuthentication -server $vrmsFqdn -user admin -pass $vrmsAdminPass -ErrorAction SilentlyContinue Error Message: Cannot bind argument to parameter 'Exception' because it is null.

```

Refer https://racetrack.eng.vmware.com/resultdetails.php?id=1264629796&resultid=25949970&view=false&failonly=No

**Comment by tenthirtyam** [comment]
Likely similar to this previous item. https://github.com/vmware/power-validated-solutions-for-cloud-foundation/pull/292/files

May need to modify `Request-VrmsToken` to check not just for Core but the OS.

```powershell
if ($PSEdition -eq "Core" -and ($PSVersionTable.OS).Split(' ')[0] -eq "Linux") {
            $vrmsResponse = Invoke-WebRequest -Method POST -Uri $uri -Headers $vrmsBasicHeader -SkipCertificateCheck -UseBasicParsing # PS Core has -SkipCertificateCheck implemented, PowerShell 5.x does not
        } else {
            $vrmsResponse = Invoke-WebRequest -Method POST -Uri $uri -Headers $vrmsBasicHeader -UseBasicParsing
        }
```
