### ISSUE TITLE
`Add-ContentLibrary` fails with error: You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by slakshmanan2706** [vmware/power-validated-solutions-for-cloud-foundation#329]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

4.5.x

### Module Version

2.6.0.1005

### PowerShell Version

7.3.6

### PowerCLI Version

13.1

### PowerVCF Version

2.3.0.1004

### Guest Operating System

windows server 2019

### Environment Details

windows server 2019 + PS Core

### Description

 Add-ContentLibrary fails with Error Message: You cannot call a method on a null-valued expression.

Doc : https://docs.vmware.com/en/VMware-Cloud-Foundation/services/vcf-developer-ready-infrastructure-v1/GUID-E18F386E-014E-410D-9A2C-8EC470B6BC18.html

### Error or Debug Output

```powershell
PS F:\platformtools> $sddcManagerFqdn = "sfo-vcf01.sfo.rainpole.io"
PS F:\platformtools> $sddcManagerUser = "administrator@vsphere.local"
PS F:\platformtools> $sddcManagerPass = "VMw@re123!"
PS F:\platformtools> $sddcDomainName = "sfo-w01"
PS F:\platformtools> $contentLibraryName = "Kubernetes"
PS F:\platformtools> Add-ContentLibrary -Server $sddcManagerFqdn -User $sddcManagerUser -Pass $sddcManagerPass -Domain $sddcDomainName -ContentLibraryName $contentLibraryName -SubscriptionUrl "https://wp-content.vmware.com/v2/latest/lib.json"
https://wp-content.vmware.com/v2/latest/lib.json
 Error at Script Line 5646
 Relevant Command: $sslThumbprint = $endpointRequest.ServicePoint.Certificate.GetCertHashString()
 Error Message: You cannot call a method on a null-valued expression.
PS F:\platformtools>

```

### Expected Behavior

Should work as expected

### Actual Behavior

 Error at Script Line 5646
 Relevant Command: $sslThumbprint = $endpointRequest.ServicePoint.Certificate.GetCertHashString()
 Error Message: You cannot call a method on a null-valued expression.

### Steps to Reproduce

Deploy VCF 4.5x env
Run the PS cmdlets mentioned in the doc

**Comment by Ashwini-Ravi** [comment]
Getting the same error in PT 5.0.9.1032 PVS PowerValidatedSolutions.2.6.0.1012. Please find the screenshot [attached[](url)]
<img width="921" alt="Screenshot 2023-08-28 at 2 15 11 PM" src="https://github.com/vmware/power-validated-solutions-for-cloud-foundation/assets/122252705/b0349612-464c-4bfc-a051-920c505d83d9">

**Comment by tenthirtyam** [comment]
I've been looking at it this morning and quickly determined that the issue is only observered in PowerShell 7.

`$endpointRequest.ServicePoint.Certificate` is always null on PowerShell 7.

PS7

```powershell
PS F:\VMware.CloudFoundation.PasswordManagement>  $endpointRequest.ServicePoint

BindIPEndPointDelegate :
ConnectionLeaseTimeout : -1
Address                : https://wp-content.vmware.com/v2/latest/lib.json
MaxIdleTime            : 100000
UseNagleAlgorithm      : True
ReceiveBufferSize      : -1
Expect100Continue      : True
IdleSince              : 8/28/2023 8:18:06 AM
ProtocolVersion        : 1.1
ConnectionName         : https
ConnectionLimit        : 2
CurrentConnections     : 0
Certificate            :
ClientCertificate      :
SupportsPipelining     : True
```

Windows PS 5.1

```powershell
C:\Users\Administrator> $endpointRequest.ServicePoint

BindIPEndPointDelegate :
ConnectionLeaseTimeout : -1
Address                : https://wp-content.vmware.com/v2/latest/lib.json
MaxIdleTime            : 100000
UseNagleAlgorithm      : True
ReceiveBufferSize      : -1
Expect100Continue      : False
IdleSince              : 8/28/2023 8:17:00 AM
ProtocolVersion        : 1.1
ConnectionName         : https
ConnectionLimit        : 2
CurrentConnections     : 1
Certificate            : System.Security.Cryptography.X509Certificates.X509Certificate
ClientCertificate      :
SupportsPipelining     : True
```

**Comment by tenthirtyam** [comment]
The following will work on PowerShell 7 (and Windows PowerShell 5.1).

```powershell
if ($subscriptionUrl) {
    $uri = New-Object System.Uri($subscriptionUrl)

    $port = if ($uri.AbsolutePath.Contains(':')) {
        $uri.AbsolutePath.Split(':')[-1] 
    } else {
        $uri.Port 
    }

    if ($port -eq -1) {
        $defaultPorts = @{ 'http' = 80; 'https' = 443 }
        $port = $defaultPorts[$uri.Scheme]
    }

    $fqdn = $uri.Host
    $port = [int]$port

    $client = New-Object System.Net.Sockets.TcpClient($fqdn, $port)
    $stream = $client.GetStream()
    $sslStream = New-Object System.Net.Security.SslStream($stream, $false, { $true })
    $sslStream.AuthenticateAsClient($fqdn)
    $sslCertificate = $sslStream.RemoteCertificate
    $sslThumbprint = $sslCertificate.GetCertHashString()
    $sslThumbprint = $sslThumbprint -replace '(..(?!$))', '$1:'

    $contentLibraryInput = @{
        Name            = $contentLibraryName
        Datastore       = $datastore
        AutomaticSync   = $true
        SubscriptionUrl = $subscriptionUrl
        SslThumbprint   = $sslThumbprint
    }
    ...
}
```

**Comment by tenthirtyam** [comment]
@slakshmanan2706 or @jshiplett - could you pick this up while I'm out of the office this week?
