### ISSUE TITLE
Add support to create an NSX credential in Aria Operations

### ISSUE THREAD

**Issue by GaryJBlake** [vmware/power-validated-solutions-for-cloud-foundation#353]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

With the switch to the new VMware Cloud Foundation Management pack we have a need to create an NSX credential in Aria Operations

### Use Case(s)

- Create an NSX Credential in Aria Operations

### Potential Configuration

NSX Credential

``` PowerShell
Add-vROPSNsxCredential -server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass VMw@re1! -domain sfo-m01 -serviceUser svc-iom-vsphere@sfo.rainpole.io -servicePassword VMw@re1!
```

NSX Client Certificate Credential

``` PowerShell
Add-vROPSNsxCredential -server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass VMw@re1! -domain sfo-m01 -certificate -certificateData server.cer  -certificateKey server.key
```

**Comment by tenthirtyam** [comment]
May need to consider both NSX Principle Identity and user/pass options.

**Comment by GaryJBlake** [comment]
Agree see use cases documented :)

**Comment by tenthirtyam** [comment]
![image](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/assets/7771363/46fc49f5-04d6-4fa6-a8b5-e7dc7c4ba841)

**Comment by GaryJBlake** [comment]
Moved to backlog as not enough time to get this one in for v2.7..0

**Comment by GaryJBlake** [comment]
Addressed in https://github.com/vmware/power-validated-solutions-for-cloud-foundation/pull/394
