### ISSUE TITLE
Error running option 14 and 15 in PlatformTools

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/power-validated-solutions-for-cloud-foundation#368]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1

### Module Version

2.7.0.1012

### PowerShell Version

7.3.6

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.3.0.1004

### Guest Operating System

windows server 2019

### Environment Details

Dual Region VCF 5.1 Testbed

### Description

Issue:

Steps to Reproduce:
1) Launch Platform tools and Run  the below options in PDR

30, 94, 14 | Management | vSphere Replication: Replace the Certificate of vSphere Replication

30, 94, 15 | Management | vSphere Replication: Register vSphere Replication with vCenter Single Sign-On

or run the below command in Powershell

Request-VrmsToken -fqdn $server -username $username-password $pass
-----------------------------------------------------
Debug:
=====
When tried to debug the issue found that the recent change made in the powervalidatedsolutions.psm1 file is causing the issue in Windows. Kindly check on this so that it is working

        if ($PSEdition -eq "Core" -and ($PSVersionTable.OS).Split(' ')[0] -eq "Linux") {

Link: 
====
https://github.com/vmware/power-validated-solutions-for-cloud-foundation/commit/1771a53c17796731a0413f02760ecd00da076d6c

Workaround:
==========
For now i have edited the file and commented  out the following code and it is working for now

if ($PSEdition -eq "Core" )#-and ($PSVersionTable.OS).Split(' ')[0] -eq "Linux")#

### Error or Debug Output

PS C:\Users\Administrator> Request-VrmsToken -fqdn $server -username $username-password $pass
Write-Error: The SSL connection could not be established, see inner exception.

### Expected Behavior

The option 14 and 15 should run without any issues

### Actual Behavior

Getting error while running the option

 The SSL connection could not be established, see inner exception.

### Steps to Reproduce

Steps to Reproduce:
1) Launch Platform tools and Run  the below options in PDR

30, 94, 14 | Management | vSphere Replication: Replace the Certificate of vSphere Replication

30, 94, 15 | Management | vSphere Replication: Register vSphere Replication with vCenter Single Sign-On

or run the below command in Powershell

Request-VrmsToken -fqdn $server -username $username-password $pass

**Comment by tenthirtyam** [comment]
I'll pick this one up. And will search for any similar instances.
