### ISSUE TITLE
Add support to verify the integration of Aria Operations in Aria Automation

### ISSUE THREAD

**Issue by tenthirtyam** [vmware/power-validated-solutions-for-cloud-foundation#45]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Develop PowerShell cmdlet(s) to enable the verification the integration of Aria Operations in Aria Automation.

This enhancement would be applicable to **Step 2** (_of 3_): 

- Verify the successful data collection for Aria Operations

### Use Case(s)

Provides an automation path for the procedure.

### Potential Configuration

To be determined during implementation.

### References

Guidance: [Verify the Integration of vRealize Automation with vRealize Operations Manager](https://docs.vmware.com/en/VMware-Cloud-Foundation/services/vcf-private-cloud-automation-v1/GUID-700AE23E-5F3E-4796-8212-6A3A686DC608.html)

**Comment by burnsjared0415** [comment]
will pick up and see what i can come up with
