### ISSUE TITLE
Error deploying Aria Automation using `VMware.PlatformTools`

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/power-validated-solutions-for-cloud-foundation#482]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

4.5.2

### Module Version

2.8.0.1046

### PowerShell Version

7.3.6

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.4.1.1000

### Guest Operating System

windows server 2019

### Description

30, 93, 5 | Management Domain | vRealize Suite Lifecycle Manager: Deploy vRealize Automation by Using vRealize Suite Lifecycle Manager

Facing issue with PCA option 5: Deploy vRealize Automation by Using vRealize Suite Lifecycle Manager

### Error or Debug Output

Error at Script Line 17892
Relevant Command: $jsonObject += [pscustomobject]@{
Error Message: You cannot call a method on a null-valued expression.

### Expected Behavior

Vra should get deployed without any issues

### Actual Behavior

Facing issues while deploying vra.

### Steps to Reproduce

30, 93, 5 | Management Domain | vRealize Suite Lifecycle Manager: Deploy vRealize Automation by Using vRealize Suite Lifecycle Manager

Facing issue with PCA option 5: Deploy vRealize Automation by Using vRealize Suite Lifecycle Manager

**Comment by tenthirtyam** [comment]
Is this error still be observed in the CI, @Ashwini-Ravi?

**Comment by Ashwini-Ravi** [comment]
> Is this error still be observed in the CI, @Ashwini-Ravi?

No i am not seeing this issue now and it can be closed
