### ISSUE TITLE
Add support to replace the SSL certificate on Aria Operations

### ISSUE THREAD

**Issue by tenthirtyam** [vmware/power-validated-solutions-for-cloud-foundation#51]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Develop PowerShell cmdlet(s) to enable the replace the SSL certificate on Aria Operations.

### Use Case(s)

Provides an automation path for the procedure.

### Potential Configuration

To be determined during implementation.

### References

Guidance: [Replace the SSL Certificate on vRealize Operations Manager](https://docs.vmware.com/en/VMware-Cloud-Foundation/services/vcf-intelligent-operations-management-v1/GUID-1B4259FC-A107-4518-BB0A-3E3D720456DF.html)

**Comment by tenthirtyam** [comment]
Use the [vRealize Suite Lifecycle Manager APIs](url)
- [Locker Certificates Controller](https://developer.vmware.com/apis/1190/vrealize-suite-lifecycle-manager#/Locker%20Certificates%20Controller)
- [Deployments Controller](https://developer.vmware.com/apis/1190/vrealize-suite-lifecycle-manager#/Deployments%20Controller)
    - Get Product Certificate
    - Update Product Certificate
   - Pre-validate Product Certificate

**Comment by GaryJBlake** [comment]
he API documentation does not seem to explicitly call out an API that covers performing an update of a certificate. I used the browser developer tools and found the following API:

"https://xint-vrslcm01.rainpole.io/lcm/lcops/api/environments/3e74dfe1-366c-486f-bfc9-625247407573/products/vrops/updatecertificate?"

Based on the above Uri I've thrown together the below function, currently triggered this on both VROPS and VRA and waiting for the outcome.



Function Update-vRSLCMProductCertificate {
    <#
        .SYNOPSIS
        Update the certificate for a product

        .DESCRIPTION
        The Update-vRSLCMProductCertificate starts the process of updating the certificate of a product in vRealize
        Suite Lifecycle Manager

        .EXAMPLE
        Update-vRSLCMProductCertificate -environmentVmId <vmid> -certificateVmId <vmid> -product vrops
        This example gets all environments in vRealize Suite Lifecycle Manager
    #>

    Param (
        [Parameter (Mandatory = $true)] [ValidateNotNullOrEmpty()] [String]$environmentVmId,
        [Parameter (Mandatory = $true)] [ValidateNotNullOrEmpty()] [String]$certificateVmId,
        [Parameter (Mandatory = $true)] [ValidateSet("vrops","vra")] [String]$product
    )

    Try {
        $body = '{
            "certificateVmId":"' + $certificateVmId +'",
            "components":[],
            "retrustProdMeta": 
                {
                    "retrustVidmCertProdList":[]
                },
                "snapshotEnabled":false
            }"'

        if ($product -eq "vrops") {
            $uri = "https://$vrslcmappliance/lcm/lcops/api/environments/$environmentVmId/products/vrops/updatecertificate?"
            
            $response = Invoke-RestMethod $uri -Method 'POST' -Headers $vrslcmHeaders -Body $body
            $response

        } elseif ($product -eq "vra") {
            $uri = "https://$vrslcmappliance/lcm/lcops/api/environments/$environmentVmId/products/vra/updatecertificate?"
            $response = Invoke-RestMethod $uri -Method 'POST' -Headers $vrslcmHeaders -Body $body
            $response
        }
    } Catch {
        Write-Error $_.Exception.Message
    }
}

**Comment by tenthirtyam** [comment]
very nice!

**Comment by tenthirtyam** [comment]
How'd the test go?

**Comment by tenthirtyam** [comment]
> ...
> Based on the above Uri I've thrown together the below function, currently triggered this on both VROPS and VRA and waiting for the outcome.

What was the outcome of the tests for this function? Looked quite promising!

**Comment by tenthirtyam** [comment]
With the transition to the Aria Operations cloud proxies, this procedure no longer needs to e automated in the solution.
