### ISSUE TITLE
Add support to configure log forwarder filters in Aria Operations for Logs

### ISSUE THREAD

**Issue by tenthirtyam** [vmware/power-validated-solutions-for-cloud-foundation#55]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Develop PowerShell cmdlet(s) to configure event forwarding filters in vRealize Log Insight - prevents duplication of log data across vRealize Log Insight clusters.

### Use Case(s)

Provides an automation path for the procedure.

### Potential Configuration

To be determined during implementation.

### References

Guidance: [Configure Event Forwarding Filters to Prevent Duplicating Log Data in vRealize Log Insight](https://docs.vmware.com/en/VMware-Cloud-Foundation/services/vcf-intelligent-logging-and-analytics-v1/GUID-CEE08269-7B6F-4869-9DB9-D17E096240FF.html)

**Comment by tenthirtyam** [comment]
### APIs

<details>
<summary>Return Log Filter</summary>
</br>

**GET**: `/api/v2/log-filter`

```powershell
$uri = "https://sfo-vrli01.sfo.rainpole.io/api/v2/log-filter"
$response = Invoke-RestMethod -Method GET -Uri $uri -Headers $vrliHeaders
$response.filters
```

</details>


<details>
<summary>Add Log Filter</summary>
</br>

**POST**: `/api/v2/log-filter`

```powershell
$uri = "https://sfo-vrli01.sfo.rainpole.io/api/v2/log-filter"
$response = Invoke-RestMethod -Method POST -Uri $uri -Headers $vrliHeaders -Body $body
$response.filters
```

`$body =`

```json
{
  "name": "filter-rule",
  "enabled": true,
  "filter": "hostname=~\"lax-vrli01.lax.rainpole.io*\""
}
```

Schema:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "pattern": "^[a-zA-Z0-9_-]*$"
    },
    "enabled": {
      "type": "boolean",
      "default": true
    },
    "filter": {
      "type": "string",
      "default": ""
    }
  },
  "required": [ "name" ]
}
```
</details>

<details>
<summary>Return Log Filter by ID</summary>
</br>

**GET** `/api/v2/log-filter/{id}`

```powershell
$id = "04f98100-995b-3f56-b321-0e10f21ee022"
$uri = "https://sfo-vrli01.sfo.rainpole.io/api/v2/log-filter/$id"
$response = Invoke-RestMethod -Method GET -Uri $uri -Headers $vrliHeaders
$response.filters
```

</details>

<details>
<summary>Update Log Filter by ID</summary>
</br>

**PATCH** `/api/v2/log-filter/{id}`

```powershell
$id = "04f98100-995b-3f56-b321-0e10f21ee022"
$uri = "https://sfo-vrli01.sfo.rainpole.io/api/v2/log-filter/$id"
$response = Invoke-RestMethod -Method PATCH -Uri $uri -Headers $vrliHeaders -Body $body
```

`$body =`

```json
{
  "enabled": true
}
```

Schema:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "type": "object",
  "properties": {
    "enabled": {
      "type": "boolean"
    },
    "filter": {
      "type": "string"
    }
  }
}
```
</details>


<details>
<summary>Delete Log Filter by ID</summary>
</br>

**DELETE** `/api/v2/log-filterr/{id}`

```powershell
$id = "04f98100-995b-3f56-b321-0e10f21ee022"
$uri = "https://sfo-vrli01.sfo.rainpole.io/api/v2/log-filter/$id"
$response = Invoke-RestMethod -Method DELETE-Uri $uri -Headers $vrliHeaders
```

</details>

**Comment by tenthirtyam** [comment]
### APIs

<details>
<summary>Update Log Forwarder by ID</summary>
</br>

**PATCH** `/api/v2/log-forwarder/{id}`

```powershell
$id = "04f98100-995b-3f56-b321-0e10f21ee022"
$uri = "https://sfo-vrli01.sfo.rainpole.io/api/v2/log-forwarder/$id"
$response = Invoke-RestMethod -Method PATCH -Uri $uri -Headers $vrliHeaders -Body $body
```

`$body =`

```json
    {
      "acceptCert": false,
      "name": "lax-vrlo01.lax.rainpole.io",
      "host": "lax-vrlo01.lax.rainpole.io",
      "port": 9000,
      "protocol": "cfapi",
      "sslEnabled": false,
      "workerCount": 8,
      "diskCacheSize": 104857600,
      "tags": {},
      "filter": "",
      "transportProtocol": null,
      "forwardComplementaryFields": true,
      "testConnection": false,
    }
```
</details>

**Comment by GaryJBlake** [comment]
The prerequisite functions have been added for log forwarder destination; however, additioanl functions are needed for to support automating this task.

- Tag(s) (Add/Remove)
- Filter (Add/Remove)

These functions should consume the Get-vRLILogForwarder and Update-vRLILogForwarder helper functions.

Tags: Note that tags are in an format where the user provides a set of comma seperated key/value pairs (e.g., "region=sfo,env=prod"). The PATCH for the log forwarder should be ideal once the ID is obtained. However, to obtain the ID the name, fwdn, protocol, and port are needed to find the unique item.
