### ISSUE TITLE
ILA: Issue while installing Workspace ONE Access Content Pack

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/power-validated-solutions-for-cloud-foundation#550]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1

### Module Version

2.9.0.1047

### PowerShell Version

7.3.6

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.4.1.1000

### Guest Operating System

windows server 2019

### Description

Issue while running Invoke-ILAdeployment at step Install Workspace ONE Access Content Pack

### Error or Debug Output

[INFO] Install Workspace ONE Access Content Pack

 [INFO] Error at Script Line 15391[0m

[INFO] Relevant Command: $response = Invoke-RestMethod -Method 'GET' -Uri $Uri -Headers $ghHeaders

[INFO] Error Message: Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

[ERROR] Exception calling "FromBase64String" with "1" argument(s): "The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters."

### Expected Behavior

There should not any errors while running Invoke-ILAdeployment

### Actual Behavior

Error while installing Workspace ONE Access Content Pack

### Steps to Reproduce

Run Invoke-ILAdeployment and it will fail at step Install Workspace ONE Access Content Pack

**Comment by tenthirtyam** [comment]
Can you test the function to install the content pack directly to see if it fails?
