### ISSUE TITLE
Re-branding: update the file name from vcdr-vsphere-integration.role to vlcr-vsphere-integration.role 

### ISSUE THREAD

**Issue by slakshmanan2706** [vmware/power-validated-solutions-for-cloud-foundation#574]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

As VMware Cloud DR has been re-branded to VMware Live Cyber Recovery, please change the file name in the following dir from vcdr-vsphere-integration.role to vlcr-vsphere-integration.role.

Dir:-
Documents\PowerShell\Modules\PowerValidatedSolutions\2.9.0.1051\vSphereRoles

### Use Case(s)

To create the required roles for VLCR and VC integration. 

### Potential Configuration

VCF 5.1.1 & VLCR v27m1

**Comment by tenthirtyam** [comment]
You can use `git mv` versus a file rename.
