### ISSUE TITLE
Bug: Error while Provisioning Tanzu kubernetes cluster during Invoke-DRI deployment

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/power-validated-solutions-for-cloud-foundation#590]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1

### Module Version

2.10.0.1011

### PowerShell Version

7.3.6

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.4.1.1000

### Guest Operating System

windows server 2019

### Description

Bug: Error while Provisioning Tanzu kubernetes cluster during Invoke-DRI deployment

Error:
Warning: v1alpha1 version of run.tanzu.vmware.com/TanzuKubernetesCluster is deprecated. Please use v1alpha3 or above
Error from server (BadRequest): error when creating "F:\\platformtools\\generatedJsons\\sfo-w01-tkc01.yaml": TanzuKubernetesCluster in version "v1alpha1" cannot be handled as a TanzuKubernetesCluster: strict decoding error: unknown field "distribution", unknown field "settings"

### Error or Debug Output

'''POWERSHELL
 [04-23-2024_08:22:42] [INFO] Adding Virtual Machine Class (guaranteed-small) to Namespace (sfo-w01-tkc01): SUCCESSFUL
 [04-23-2024_08:22:42] [INFO] Provisioning a Tanzu Kubernetes Cluster for Developer Ready Infrastructure for VMware Cloud Foundation
Warning: v1alpha1 version of run.tanzu.vmware.com/TanzuKubernetesCluster is deprecated. Please use v1alpha3 or above
Error from server (BadRequest): error when creating "F:\\platformtools\\generatedJsons\\sfo-w01-tkc01.yaml": TanzuKubernetesCluster in version "v1alpha1" cannot be handled as a TanzuKubernetesCluster: strict decoding error: unknown field "distribution", unknown field "settings"
 [04-23-2024_08:22:51] [INFO] Creating Tanzu Kubernetes Cluster in Supervisor Cluster (sfo-w01-cl01) using YAML (F:\platformtools\generatedJsons\sfo-w01-tkc01.yaml): SUCCESSFUL
 [04-23-2024_08:22:51] [NOTE] Finished Deployment of Developer Ready Infrastructure for VMware Cloud Foundation
'''

### Expected Behavior

There should not be any errors during deployment

### Actual Behavior

Getting error validating Tanzu Kubernetes cluster

### Steps to Reproduce

Run Invoke-DRI deployment from PVS

**Comment by GaryJBlake** [comment]
Issue seems to be related to the content of the yaml file

**Comment by GaryJBlake** [comment]
Couple of issues identified as follows:

- YAML formatting issues, looks like when the module was saved the layout of the YAML object got adjusted to tabs instead of 2 space indent
- For VCF 4.5.2 the vSphere version is vSphere 7 and needs version v1.24 and not v1.24
