### ISSUE TITLE
ILA: Issue while connecting vi workload domain during  Invoke-ILA deployment 

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/power-validated-solutions-for-cloud-foundation#595]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1

### Module Version

2.10.0.1024

### PowerShell Version

7.3.6

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.4.1.1000

### Guest Operating System

windows server 2019

### Description

Issue while running Invoke-ILAdeployment at step Connecting VI Workload Domains to VMware Aria Operations for Logs

### Error or Debug Output

[ERROR] Workload Domain Intergration in VMware Aria Operations for Logs (sfo-vrli01.sfo.rainpole.io) for Workload Domain (sfo-w01): POST_VALIDATION_FAILED

### Expected Behavior

There should not any errors while running Invoke-ILAdeployment

### Actual Behavior

Issue while running Invoke-ILAdeployment at step Connecting VI Workload Domains to VMware Aria Operations for Logs

### Steps to Reproduce

Run Invoke-ILAdeployment and it will fail at step Connecting VI Workload Domains to VMware Aria Operations for Logs

**Comment by GaryJBlake** [comment]
Environmental issue due to failure in SDDC Manager, not related to `PowerValidatedSolutions` code
