### ISSUE TITLE
Bug: Issue while running Invoke-Vrslcm deployment in vcf 5.1.0

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/power-validated-solutions-for-cloud-foundation#629]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1.0

### Module Version

2.10.0.1050

### PowerShell Version

7.3.6

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.4.1.1000

### Guest Operating System

windows server 2019

### Description

Issue while running Invoke-Vrslcm deployment in vcf 5.1.0. When upgrading from 8.14.0 pspack8 to 8.16.0.4 the invoke deployment is failing

### Error or Debug Output

No upgrade available

### Expected Behavior

The upgrade should go through without any issues

### Actual Behavior

Unable to upgrade vrslcm

### Steps to Reproduce

Issue while running Invoke-Vrslcm deployment in vcf 5.1.0. When upgrading from 8.14.0 pspack8 to 8.16.0.4 the invoke deployment is failing

**Comment by GaryJBlake** [comment]
### Investigation

Seems the CD-ROM is not fully mounted before we attempt to discovery the upgrade
