### ISSUE TITLE
PDR:Getting error while running Invoke-PDR Deployment

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/power-validated-solutions-for-cloud-foundation#633]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1.1

### Module Version

2.10.1053

### PowerShell Version

7.3.6

### PowerCLI Version

13.1.0.21624340

### PowerVCF Version

2.4.1.1000

### Guest Operating System

windows server 2019

### Description

Getting error while running Invoke-PdrDeployment

### Error or Debug Output

'''POWERSHELL
[ERROR] System.Management.Automation.CmdletInvocationException:
{
  "error_code": "1.4",
  "message": "Cannot deserialize value of type \u0060java.lang.String\u0060 from Array value (token \u0060JsonToken.START_ARRAY\u0060)",
  "op_id": "88f8f628-78c8-46aa-8a7a-c9c84e5f69af"
}
 ---> Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (Bad Request).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 [05-23-2024_16:18:15] [ERROR]
{
  "error_code": "1.4",
  "message": "Cannot deserialize value of type \u0060java.lang.String\u0060 from Array value (token \u0060JsonToken.START_ARRAY\u0060)",
  "op_id": "88f8f628-78c8-46aa-8a7a-c9c84e5f69af"
}
'''

### Expected Behavior

The Invoke-pdrdeployment should run without any errors.

### Actual Behavior

We are getting errors while running Invoke-PDR deployment.

### Steps to Reproduce

Run Invoke-PdrDeployment

**Comment by GaryJBlake** [comment]
### Investigation

The issue here is the `Add-VrmsReplication` cmdlet is making an assumption about the datastore in that there will be only one, whereas the physical setup returns a single vSAN datastore and 4 local datastores. 

Function needs to be enhanced with a parameter to pass in the datastore name and then `Add-VsphereReplication` needs to establish the primary datastore for the recovery site from SDDC Manager inventory.
