### ISSUE TITLE
Installing module/disconnected environment/windows is wrong

### ISSUE THREAD

**Issue by iciblabla** [vmware/power-validated-solutions-for-cloud-foundation#636]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Module Version

ALL

### Motivation

https://vmware.github.io/power-validated-solutions-for-cloud-foundation/install/#__tabbed_2_1

In installation, disconnected environement, windows documentation mention

Import-Module -Name VMware.PowerCLI -Path F:\Module\ -Repository PSGallery
Import-Module -Name VMware.vSphere.SsoAdmin -Path F:\Module\ -Repository PSGallery
Import-Module -Name PowerVCF -Path F:\Module\ -Repository PSGallery
Import-Module -Name PowerValidatedSolutions -Path F:\Module\ -Repository PSGallery
Import-Module -Name ImportExcel -Path F:\Module\ -Repository PSGallery

and should be 

Save-Module -Name VMware.PowerCLI -Path F:\Module\ -Repository PSGallery
Save-Module -Name VMware.vSphere.SsoAdmin -Path F:\Module\ -Repository PSGallery
Save-Module -Name PowerVCF -Path F:\Module\ -Repository PSGallery
Save-Module -Name PowerValidatedSolutions -Path F:\Module\ -Repository PSGallery
Save-Module -Name ImportExcel -Path F:\Module\ -Repository PSGallery

It's correct for linux tab.

### Suggestion

https://vmware.github.io/power-validated-solutions-for-cloud-foundation/install/#__tabbed_2_1

In installation, disconnected environement, windows documentation mention

Import-Module -Name VMware.PowerCLI -Path F:\Module\ -Repository PSGallery
Import-Module -Name VMware.vSphere.SsoAdmin -Path F:\Module\ -Repository PSGallery
Import-Module -Name PowerVCF -Path F:\Module\ -Repository PSGallery
Import-Module -Name PowerValidatedSolutions -Path F:\Module\ -Repository PSGallery
Import-Module -Name ImportExcel -Path F:\Module\ -Repository PSGallery

and should be 

Save-Module -Name VMware.PowerCLI -Path F:\Module\ -Repository PSGallery
Save-Module -Name VMware.vSphere.SsoAdmin -Path F:\Module\ -Repository PSGallery
Save-Module -Name PowerVCF -Path F:\Module\ -Repository PSGallery
Save-Module -Name PowerValidatedSolutions -Path F:\Module\ -Repository PSGallery
Save-Module -Name ImportExcel -Path F:\Module\ -Repository PSGallery

It's correct for linux tab.

**Comment by tenthirtyam** [comment]
Resolved in [b944d5c](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/commit/b944d5c2c4bea94da924d1155d30168488ac4a77).
