### ISSUE TITLE
Add pre-check for NSX Federation before deployment.

### ISSUE THREAD

**Issue by nthaler-vmware** [vmware/power-validated-solutions-for-cloud-foundation#708]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/power-validated-solutions-for-cloud-foundation/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.2

### Module Version

2.11.0.1057

### PowerShell Version

7.4.4

### PowerCLI Version

13.3

### PowerVCF Version

2.4.1.1000

### Guest Operating System

Windows Server 2019

### Description

PDR depends on a L2 Stretch between site A and site B with a MGMT segment under the same name in both sites. 

However, the pre-check does not validate this.  

### Error or Debug Output

```comsole
08-07-2024_08:23:22] [INFO] Configuring Network Mappings between the Protected and the Recovery VMware Cloud Foundation Instances

Error at Script Line 3137

Relevant Command: $StatusMsg = Add-SrmMapping -sddcManagerAFqdn $jsonInput.protected.sddcManagerFqdn -sddcManagerAUser $jsonInput.protected.sddcManagerUser -sddcManagerAPass $jsonInput.protected.sddcManagerPass -sddcManagerBFqdn $jsonInput.recovery.sddcManagerFqdn -sddcManagerBUser $jsonInput.recovery.sddcManagerUser -sddcManagerBPass $jsonInput.recovery.sddcManagerPass -type "network" -protected $jsonInput.protected.networkSegment -recovery $jsonInput.recovery.networkSegment -WarningAction SilentlyContinue -ErrorAction SilentlyContinue -WarningVariable WarnMsg -ErrorVariable ErrorMsg

Error Message: 8/7/2024 08:23:28       Get-VirtualNetwork              VirtualNetwork with name 'xint-m01-seg01' was not found using the specified filter(s).
```

### Expected Behavior

Pre-check should throw an error if NSX Federation is not enabled.

Error message should specify which site the network segment is missing on.

### Actual Behavior

Pre-check does not include NSX Federation validatiom.

### Steps to Reproduce

Do not install NSX Federation and run PDR.

**Comment by nthaler-vmware** [comment]
... of conversely, allow an option to create a segment with the same name assuming a VLAN backed port-group so the segment exists on both sides

**Comment by tenthirtyam** [comment]
Error message formatted and updated to an `enhancement`.
